all:
	g++ chat_client.cpp -l ws2_32 -I . -o chat_client.exe
	g++ chat_server.cpp -l ws2_32 -I . -o chat_server.exe
c:
	g++ chat_client.cpp -l ws2_32 -I . -o chat_client.exe
s:
	g++ chat_server.cpp -l ws2_32 -I . -o chat_server.exe
clean:
	rm chat_client.exe
	rm chat_server.exe