all:
	g++ udp_sender.cpp -l ws2_32 -I . -o sender.exe
	g++ udp_recver.cpp -l ws2_32 -I . -o recver.exe
s:
	g++ udp_sender.cpp -l ws2_32 -I . -o sender.exe
r:
	g++ udp_recver.cpp -l ws2_32 -I . -o recver.exe
clean:
	del .\recvfile\*